default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME', 'taskman').parameterize.underscore}_development" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME', 'taskman').parameterize.underscore}_test" %>

production:
  <<: *default
  database: taskman_production
  username: taskman
  password: <%= ENV["TASKMAN_DATABASE_PASSWORD"] %>
